services:
  ota-server:
    build: .
    image: ota-server:latest
    container_name: ota-server
    environment:
      OTA_CONFIG: /app/server/config/server.yml
    ports:
      - "8443:8443"
    volumes:
      - ./server/config:/app/server/config:ro
      - ./server/certs:/app/server/certs:ro
      - ./server/firmware_store:/app/server/firmware_store
      - ./server/ota.db:/app/server/ota.db
    restart: unless-stopped
